branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: MeGo
  branch: null
  default_platform: IIS 10.0 running on 64bit Windows Server 2025
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
